const express = require('express');
const uuid = require('uuid').v4;

const router = express.Router();

router.post('/', (req, res) => {
    /**
        request:
            {
                token: string, // token from retain
                amount: number, // integer of smallest currency unit
                order_id: string, // public order id
                currency: string, // currency code
                billing_address: {},
                shipping_address: {},
                order_details: {} // if additional_order_details is true
            }

        response: 
            200:
                {
                    authorization_id: string, // id generated by your application
                    payment_details: {}, // whatever you want
                    requires_action: boolean, // true if SCA action needed
                    avs_response: string, // AVS response code
                    cvd_response: string, // CVD response code
                }
            4xx/5xx:
                {
                    error_code: string,
                    message: string,
                }
        
     */
    res.status(200);
    res.send({
        authorization_id: uuid(),
        payment_details: {},
        requires_action: false,
        avs_response: 'Y', // Street address and 5-digit zip match
        cvd_response: 'M', // Moneris match
    });
});

module.exports = router;